runtime:
  threads: 4

logging:
  level: netgauze_collector=trace,netgauze_yang_push=trace,info
  ansi: true

telemetry:
  url: http://localhost:4317/v1/metrics
  id: netgauze-udpnotif-telemetry
  exporter_timeout: 3000
  reader_interval: 60000
  reader_timeout: 3000

udp_notif:
  subscriber_timeout: 100
  listeners:
    - address: "[::]:10000"
      workers: 2
    # - address: "[::]:10100"
    - address: "0.0.0.0:10100"
      workers: 2

  netconf:
    username: daisy1
    private_key_path: /home/taarole8/.ssh/id_rsa-dev-env
    port: 830
    # username: dsy-taarole8
    # private_key_path: /home/taarole8/.ssh/id_rsa_netconf-ietf-lab
    # port: 830

  # cache_location: /home/taarole8/tmp/netgauze-udpnotif-telemetry-cache
  # cache_location: /tmp/test_cache
  cache_location: kafka-yang-producer-cache

  publishers:
    group1:
      buffer_size: 1000
      enrichment:
        inputs:
          # files:
          #   poll_interval_seconds: 10
          #   paths:
          #     - path: assets/inputs/files/yang-push-upserts.jsonl
          #       format: !YangPushUpserts
          kafka:
            # consumers:
            # - topic: daisy.dev.cosmos-sonata-nodes-json
            #   message_format: !Sonata
            #   weight: 64
            #   consumer_config:
            #     metadata.broker.list: "kafka.sbd.corproot.net:9093"
            #     security.protocol: "ssl"
            #     ssl.certificate.location: "/home/taarole8/sbd_ssl/collectors.crt"
            #     ssl.key.location: "/home/taarole8/sbd_ssl/collectors.key"
            #     ssl.ca.location: "/home/taarole8/sbd_ssl/sbd_root_ca.crt"
            #     group.id: daisy.dev.taarole8-testing
            #     enable.auto.commit: "false"
            #     auto.offset.reset: earliest
            consumers:
              - topic: sonata
                message_format: !Sonata
                weight: 64 # default: 64
                consumer_config:
                  bootstrap.servers: localhost:49092
                  group.id: taarole8-rocky8-avro
                  enable.auto.commit: "false"
                  auto.offset.reset: earliest
      custom_yang_schemas: # any overrides, empty for now
      endpoints:
        # json-endpoint: !TelemetryKafkaJson
        #   topic: telemetry-message-json
        #   producer_config:
        #     bootstrap.servers: localhost:49092
        #     message.timeout.ms: "60000"
        #     queue.buffering.max.messages: "1000"
        #   writer_id: coll-netgauze-telemetry-json
        yang-endpoint: !TelemetryKafkaYang
          topic: telemetry-message-yang
          # schema_registry_url: http://localhost:48081
          # schema_registry_url: https://schema-registry.stage.odp-int.corproot.net
          # schema_registry_url: "http://10.250.99.20"
          schema_registry_url: "https://schema-registry-sc.olt.stage.sbd.corproot.net" # integration SBD
          producer_config:
            bootstrap.servers: localhost:49092
            message.timeout.ms: "60000"
            queue.buffering.max.messages: "1000"
          writer_id: coll-netgauze-telemetry-yang
          yang_converter:
            subject_prefix: daisy.dev.
            root_schema_name: ietf-telemetry-message
            default_yang_lib_ref:
              content_id: ietf-telemetry-message-full
              yang_library_path: assets/yang/ietf-telemetry-message/yang-lib-full.xml
              yang_lib_ref_path: assets/yang/ietf-telemetry-message/
            extension_yang_lib_ref:
              content_id: ietf-telemetry-message-min
              yang_library_path: assets/yang/ietf-telemetry-message/yang-lib-min.xml
              yang_lib_ref_path: assets/yang/ietf-telemetry-message
